import 'package:flutter/cupertino.dart';

TextEditingController phaNameController = TextEditingController();
TextEditingController emailController = TextEditingController();
TextEditingController passwordController = TextEditingController();
TextEditingController phaCodeController = TextEditingController();
TextEditingController properityIdController = TextEditingController();
TextEditingController inspectoridController = TextEditingController();
TextEditingController owneridController = TextEditingController();
TextEditingController ownernameController = TextEditingController();
TextEditingController inspectiondateController = TextEditingController();
TextEditingController inspectiontimeController = TextEditingController();
TextEditingController unitidController = TextEditingController();
TextEditingController unitaddressline1Controller = TextEditingController();
TextEditingController unitaddressline2Controller = TextEditingController();
TextEditingController cityController = TextEditingController();
TextEditingController stateController = TextEditingController();
TextEditingController zipcodeController = TextEditingController();
TextEditingController zipplusController = TextEditingController();
TextEditingController confrimdecisionpagecontroller = TextEditingController();
TextEditingController unsuccessfulController = TextEditingController();
